version: "3"
services:
  postgres:
    image: postgres:12
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      .env

      #  backend:
      #    build:
      #      dockerfile: Dockerfile
      #      context: imdb-graphql
      #    volumes:
      #      - ./data:/tmp/data
      #    ports:
      #      - "5000:5000"
      #    env_file:
      #      .env
